"""
Module for plotting the pathfinding process on a matrix representation of the world.
Generated by copilot
"""

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import Line2D
from src.world import World


class MatrixPlotter:
    def __init__(self, world, solution, explored, frontier, initial_state, goal_state):
        self.world = world
        self.solution = solution
        self.explored = explored
        self.frontier = frontier
        self.initial_state = initial_state
        self.goal_state = goal_state

    def plot(self):
        # Create a numeric matrix representation (0 for obstacles, 1 for accessible)
        rows = len(self.world)
        cols = len(self.world[0]) if rows > 0 else 0
        matrix = np.zeros((rows, cols))

        # Mark accessible cells as 1, obstacles as 0
        for row in range(rows):
            for col in range(cols):
                if self.world[row][col] != "-":
                    matrix[row][col] = 1

        fig, ax = plt.subplots(figsize=(10, 8))

        # Display the world map
        ax.imshow(matrix, cmap="Greys", interpolation="nearest", alpha=0.3)

        # Mark initial and goal states
        initial_pos = World.find_position(self.initial_state)
        goal_pos = World.find_position(self.goal_state)

        legend_elements = []

        if initial_pos:
            ax.scatter(
                initial_pos[1],
                initial_pos[0],
                color="red",
                s=200,
                marker="o",
                edgecolors="darkred",
                linewidth=2,
                zorder=5,
            )
            legend_elements.append(
                Line2D(
                    [0],
                    [0],
                    marker="o",
                    color="w",
                    markerfacecolor="red",
                    markeredgecolor="darkred",
                    markersize=10,
                    label="Start",
                )
            )

        if goal_pos:
            ax.scatter(
                goal_pos[1],
                goal_pos[0],
                color="yellow",
                s=200,
                marker="o",
                edgecolors="orange",
                linewidth=2,
                zorder=5,
            )
            legend_elements.append(
                Line2D(
                    [0],
                    [0],
                    marker="o",
                    color="w",
                    markerfacecolor="yellow",
                    markeredgecolor="orange",
                    markersize=10,
                    label="Goal",
                )
            )

        ax.set_title(
            "Pathfinding Visualization A* Algorithm", fontsize=14, fontweight="bold"
        )
        ax.set_xlabel("Column")
        ax.set_ylabel("Row")
        ax.set_xticks(range(cols))
        ax.set_yticks(range(rows))
        ax.grid(True, alpha=0.3)

        ax.legend(handles=legend_elements, loc="upper center")
        plt.tight_layout()
        plt.draw()
        plt.pause(0.5)

        # Animate explored nodes one by one with 1 second pause
        explored_added = False
        for node in self.explored:
            pos = World.find_position(node.state)
            if pos:
                ax.scatter(pos[1], pos[0], color="blue", s=100, marker="o", alpha=0.6)

                if not explored_added:
                    legend_elements.append(
                        Line2D(
                            [0],
                            [0],
                            marker="o",
                            color="w",
                            markerfacecolor="blue",
                            markersize=8,
                            alpha=0.6,
                            label="Explored",
                        )
                    )
                    ax.legend(handles=legend_elements, loc="upper center")
                    explored_added = True

                plt.draw()
                plt.pause(1)

        # Extract positions from frontier nodes and mark them all at once
        frontier_added = False
        for node in self.frontier:
            pos = World.find_position(node.state)
            if pos:
                ax.scatter(pos[1], pos[0], color="purple", s=100, marker="s", alpha=0.6)

                if not frontier_added:
                    legend_elements.append(
                        Line2D(
                            [0],
                            [0],
                            marker="s",
                            color="w",
                            markerfacecolor="purple",
                            markersize=8,
                            alpha=0.6,
                            label="Frontier",
                        )
                    )
                    ax.legend(handles=legend_elements, loc="upper center")
                    frontier_added = True

        # Mark the solution path
        solution_positions = []
        for state in self.solution:
            pos = World.find_position(state)
            if pos:
                solution_positions.append(pos)
                ax.scatter(pos[1], pos[0], color="green", s=100, marker="*", alpha=0.8)

        # Draw lines connecting the solution path
        if solution_positions:
            solution_positions_array = np.array(solution_positions)
            ax.plot(
                solution_positions_array[:, 1],
                solution_positions_array[:, 0],
                color="green",
                linewidth=2,
                alpha=0.5,
            )

            legend_elements.append(
                Line2D(
                    [0],
                    [0],
                    marker="*",
                    color="w",
                    markerfacecolor="green",
                    markersize=10,
                    alpha=0.8,
                    label="Solution",
                )
            )
            ax.legend(handles=legend_elements, loc="upper center")

        plt.draw()
        plt.show()
